version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12

  build:
    commands:
      - cd website
      - npm ci
      - npm run build
      - aws s3 cp build s3://${WEBSITE_BUCKET} --recursive
