version: 0.2

env:
  variables:
    SLS_DEBUG: "*"

phases:
  install:
    runtime-versions:
      nodejs: 12
      python: 3.8
    commands:
      - npm install --unsafe-perm -g serverless
      - cd services
      - npm ci

  build:
    commands:
      # - docker-compose up --detach
      # - sleep 15 # So that localstack has a chance to start up before we test against it
      # - npm run test:coverage
      - serverless deploy --region ${AWS_REGION}

cache:
  paths:
    - "services/node_modules/**/*"
    - "/root/.npm/**/*"
    - "/usr/local/lib/node_modules/serverless/**/*"

# reports: #New
#   QuoteOfTheDayServiceReports:
#     files: #Store all of the files
#       - 'junit.xml'
#     base-directory: 'services' # Location of the reports
