AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ParamDynamoDbEncryptionKey:
    Type: String
    Description: '(Optional): The KMS key ID, Amazon Resource Name (ARN), alias name, or alias ARN to use. If not provided then the default KMS key is used.'
    Default: 'alias/aws/dynamodb'
  ParamDynamoDbQuotesTableName:
    Type: String
    AllowedPattern: '[a-zA-Z0-9_.-]+'
  ParamBucketPrefix:
    Type: String

Resources:

  QuotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions: 
        - AttributeName: 'PK'
          AttributeType: 'S'
        - AttributeName: 'SK'
          AttributeType: 'S'
        - AttributeName: 'GSI1PK'
          AttributeType: 'S'
        - AttributeName: 'GSI1SK'
          AttributeType: 'S'
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: BookList
          KeySchema:
            - AttributeName: 'GSI1PK'
              KeyType: 'HASH'
            - AttributeName: 'GSI1SK'
              KeyType: 'RANGE'
          Projection:
            NonKeyAttributes:
              - 'Title'
              - 'Author'
            ProjectionType: INCLUDE # ALL | INCLUDE | KEYS_ONLY
      KeySchema:
        - AttributeName: 'PK'
          KeyType: 'HASH'
        - AttributeName: 'SK'
          KeyType: 'RANGE'
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        KMSMasterKeyId: !Ref ParamDynamoDbEncryptionKey
        SSEEnabled: true
        SSEType: KMS
      StreamSpecification:
        StreamViewType: KEYS_ONLY # KEYS_ONLY | NEW_IMAGE | OLD_IMAGE | NEW_AND_OLD_IMAGES
      TableName: !Ref ParamDynamoDbQuotesTableName
      # TimeToLiveSpecification:
      #   AttributeName: String
      #   Enabled: Boolean

  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Sub '${ParamBucketPrefix}-website'

  LogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: LogDeliveryWrite
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Sub '${ParamBucketPrefix}-logs'

Outputs:
  QuotesTableName:
    Value: !Ref QuotesTable
  QuotesTableArn:
    Value: !GetAtt QuotesTable.Arn
  QuotesTableStreamArn:
    Value: !GetAtt QuotesTable.StreamArn
  WebsiteBucketName:
    Value: !Ref WebsiteBucket
  WebsiteBucketArn:
    Value: !GetAtt WebsiteBucket.Arn
  WebsiteBucketDomainName:
    Value: !GetAtt WebsiteBucket.DomainName
  WebsiteBucketDualStackDomainName:
    Value: !GetAtt WebsiteBucket.DualStackDomainName
  WebsiteBucketRegionalDomainName:
    Value: !GetAtt WebsiteBucket.RegionalDomainName
  WebsiteBucketWebsiteURL:
    Value: !GetAtt WebsiteBucket.WebsiteURL
  LogsBucketName:
    Value: !Ref LogsBucket
  LogsBucketArn:
    Value: !GetAtt LogsBucket.Arn
  LogsBucketDomainName:
    Value: !GetAtt LogsBucket.DomainName
  LogsBucketDualStackDomainName:
    Value: !GetAtt LogsBucket.DualStackDomainName
  LogsBucketRegionalDomainName:
    Value: !GetAtt LogsBucket.RegionalDomainName
  LogsBucketWebsiteURL:
    Value: !GetAtt LogsBucket.WebsiteURL
